site_name: Diffit
site_url: https://loum.github.io/diffit/

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - diffit:
    - utilities/index.md
    - row:
      - utilities/diffit/row/index.md
      - utilities/diffit/row/csv.md
      - utilities/diffit/row/parquet.md
    - analyse:
      - utilities/diffit/analyse/index.md
      - utilities/diffit/analyse/distinct.md
      - utilities/diffit/analyse/altered.md
    - columns:
      - utilities/diffit/columns/index.md
      - utilities/diffit/columns/diff.md
    - convert:
      - utilities/diffit/convert/index.md
      - utilities/diffit/convert/csv.md
  - Scaling out: containerisation.md
  - Reference:
    - diffit:
      - datastore:
        - reference/diffit/datastore/spark.md
      - reference/diffit/reporter.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - header.autohide
    - content.code.copy

plugins:
  - search
  - mkdocstrings

watch:
  - ../src/diffit
